apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'services'
        static_configs:
          - targets:
            - user-service.project4.svc.cluster.local:3001
            - product-service.project4.svc.cluster.local:3002
            - order-service.project4.svc.cluster.local:3003
            - payment-service.project4.svc.cluster.local:3004