apiVersion: v1
kind: Pod
metadata:
  name: mongo-user
  namespace: project4
spec:
  containers:
    - name: mongo
      image: mongo
      ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-user
  namespace: project4
spec:
  ports:
    - port: 27017