apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: project4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: anandhukdevops/payment-service
          ports:
            - containerPort: 3004
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: project4
spec:
  selector:
    app: payment-service
  ports:
    - port: 3004
      targetPort: 3004